import type { ExtendedModelDescriptor } from '@coco/protocol';

/**
 * Seed Model Registry — maps provider models to COCO capabilities.
 * Extends Deep Spec 4 §3.2 with all configured keys (Groq, Anthropic, OpenAI, DeepSeek, Google, OpenRouter).
 */
export const BUILTIN_MODEL_REGISTRY: ExtendedModelDescriptor[] = [
  // ─── ANTHROPIC ──────────────────────────────────────────────────────────
  {
    model_id: 'anthropic/claude-3-5-sonnet@20241022',
    provider: 'anthropic',
    family: 'claude',
    display_name: 'Claude 3.5 Sonnet',
    tier: 'frontier',
    license: 'commercial_hosted',
    deployment_mode: 'hosted_api',
    context_window_tokens: 200000,
    max_output_tokens: 8192,
    capabilities: [
      { capability_id: 'reason.deep', declared_quality_score: 0.98, preferred: true },
      { capability_id: 'reason.standard', declared_quality_score: 0.96, preferred: true },
      { capability_id: 'reason.tool_augmented', declared_quality_score: 0.97, preferred: true },
      { capability_id: 'code.gen.repo', declared_quality_score: 0.96, preferred: true },
      { capability_id: 'code.edit', declared_quality_score: 0.95, preferred: true },
      { capability_id: 'code.review', declared_quality_score: 0.96, preferred: true },
      { capability_id: 'research.synthesize', declared_quality_score: 0.95, preferred: true },
      { capability_id: 'structured.extract', declared_quality_score: 0.94, preferred: true },
    ],
    cost: { input_per_million_usd: 3.0, output_per_million_usd: 15.0, cached_input_per_million_usd: 0.3 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: true,
      supports_vision: true,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: true,
      supports_streaming: true,
      supports_reasoning: true,
      supports_caching: true,
      supports_batch: false,
      max_tools_per_request: 64,
      max_images_per_request: 20,
    },
    endpoints: [
      {
        endpoint_id: 'anthropic-primary',
        base_url: 'https://api.anthropic.com',
        region: 'us-east-1',
        max_concurrent_requests: 50,
        supports_streaming: true,
        credential_env_var: 'ANTHROPIC_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 1000, tokens_per_minute: 400000, concurrent_requests: 50, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 1200, p95_latency_ms: 3500, reliability_score: 0.99 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal', 'confidential', 'restricted'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  // ─── GROQ (High-Speed Models & Systems) ─────────────────────────────────
  {
    model_id: 'groq/llama-3.3-70b-versatile',
    provider: 'groq',
    family: 'llama',
    display_name: 'Llama 3.3 70B (Groq ~280tps)',
    tier: 'advanced',
    license: 'open_weight',
    deployment_mode: 'hosted_api',
    context_window_tokens: 131072,
    max_output_tokens: 32768,
    capabilities: [
      { capability_id: 'reason.fast', declared_quality_score: 0.92, preferred: true },
      { capability_id: 'reason.standard', declared_quality_score: 0.91, preferred: true },
      { capability_id: 'code.gen.short', declared_quality_score: 0.89, preferred: true },
      { capability_id: 'translate', declared_quality_score: 0.90, preferred: true },
    ],
    cost: { input_per_million_usd: 0.59, output_per_million_usd: 0.79 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: true,
      supports_vision: false,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: true,
      supports_streaming: true,
      supports_reasoning: false,
      supports_caching: false,
      supports_batch: false,
      max_tools_per_request: 32,
      max_images_per_request: 0,
    },
    endpoints: [
      {
        endpoint_id: 'groq-primary',
        base_url: 'https://api.groq.com/openai/v1',
        region: 'us-east-1',
        max_concurrent_requests: 100,
        supports_streaming: true,
        credential_env_var: 'GROQ_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 1000, tokens_per_minute: 300000, concurrent_requests: 100, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 350, p95_latency_ms: 900, reliability_score: 0.99 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal', 'confidential'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  {
    model_id: 'groq/openai/gpt-oss-120b',
    provider: 'groq',
    family: 'gpt-oss',
    display_name: 'GPT-OSS 120B (Groq ~500tps)',
    tier: 'frontier',
    license: 'open_weight',
    deployment_mode: 'hosted_api',
    context_window_tokens: 131072,
    max_output_tokens: 65536,
    capabilities: [
      { capability_id: 'reason.deep', declared_quality_score: 0.94, preferred: true },
      { capability_id: 'reason.standard', declared_quality_score: 0.93, preferred: false },
      { capability_id: 'code.gen.repo', declared_quality_score: 0.92, preferred: false },
    ],
    cost: { input_per_million_usd: 0.15, output_per_million_usd: 0.60 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: true,
      supports_vision: false,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: true,
      supports_streaming: true,
      supports_reasoning: true,
      supports_caching: false,
      supports_batch: false,
      max_tools_per_request: 32,
      max_images_per_request: 0,
    },
    endpoints: [
      {
        endpoint_id: 'groq-primary',
        base_url: 'https://api.groq.com/openai/v1',
        region: 'us-east-1',
        max_concurrent_requests: 100,
        supports_streaming: true,
        credential_env_var: 'GROQ_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 1000, tokens_per_minute: 250000, concurrent_requests: 100, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 400, p95_latency_ms: 1100, reliability_score: 0.99 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal', 'confidential'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  {
    model_id: 'groq/compound',
    provider: 'groq',
    family: 'compound',
    display_name: 'Groq Compound Agentic System (~450tps)',
    tier: 'advanced',
    license: 'open_weight',
    deployment_mode: 'hosted_api',
    context_window_tokens: 131072,
    max_output_tokens: 8192,
    capabilities: [
      { capability_id: 'reason.tool_augmented', declared_quality_score: 0.95, preferred: true },
      { capability_id: 'research.extract', declared_quality_score: 0.93, preferred: true },
    ],
    cost: { input_per_million_usd: 0.20, output_per_million_usd: 0.50 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: true,
      supports_vision: false,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: true,
      supports_streaming: true,
      supports_reasoning: true,
      supports_caching: false,
      supports_batch: false,
      max_tools_per_request: 16,
      max_images_per_request: 0,
    },
    endpoints: [
      {
        endpoint_id: 'groq-primary',
        base_url: 'https://api.groq.com/openai/v1',
        region: 'us-east-1',
        max_concurrent_requests: 50,
        supports_streaming: true,
        credential_env_var: 'GROQ_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 200, tokens_per_minute: 200000, concurrent_requests: 50, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 500, p95_latency_ms: 1200, reliability_score: 0.98 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  // ─── DEEPSEEK ───────────────────────────────────────────────────────────
  {
    model_id: 'deepseek/deepseek-r1@latest',
    provider: 'deepseek',
    family: 'deepseek',
    display_name: 'DeepSeek R1 (Reasoning)',
    tier: 'frontier',
    license: 'open_weight',
    deployment_mode: 'hosted_api',
    context_window_tokens: 64000,
    max_output_tokens: 8192,
    capabilities: [
      { capability_id: 'reason.deep', declared_quality_score: 0.96, preferred: true },
      { capability_id: 'reason.standard', declared_quality_score: 0.92, preferred: false },
    ],
    cost: { input_per_million_usd: 0.55, output_per_million_usd: 2.19 },
    features: {
      supports_tool_calling: false,
      supports_parallel_tools: false,
      supports_vision: false,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: false,
      supports_streaming: true,
      supports_reasoning: true,
      supports_caching: false,
      supports_batch: false,
      max_tools_per_request: 0,
      max_images_per_request: 0,
    },
    endpoints: [
      {
        endpoint_id: 'deepseek-primary',
        base_url: 'https://api.deepseek.com/v1',
        region: 'us-east-1',
        max_concurrent_requests: 30,
        supports_streaming: true,
        credential_env_var: 'DEEPSEEK_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 200, tokens_per_minute: 100000, concurrent_requests: 30, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 2500, p95_latency_ms: 6000, reliability_score: 0.97 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal', 'confidential'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  // ─── OPENAI ─────────────────────────────────────────────────────────────
  {
    model_id: 'openai/gpt-4o@latest',
    provider: 'openai',
    family: 'gpt',
    display_name: 'GPT-4o',
    tier: 'frontier',
    license: 'commercial_hosted',
    deployment_mode: 'hosted_api',
    context_window_tokens: 128000,
    max_output_tokens: 16384,
    capabilities: [
      { capability_id: 'reason.standard', declared_quality_score: 0.95, preferred: false },
      { capability_id: 'code.gen.short', declared_quality_score: 0.94, preferred: false },
      { capability_id: 'vision.understand', declared_quality_score: 0.96, preferred: true },
      { capability_id: 'structured.extract', declared_quality_score: 0.95, preferred: true },
    ],
    cost: { input_per_million_usd: 2.50, output_per_million_usd: 10.00 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: true,
      supports_vision: true,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: true,
      supports_streaming: true,
      supports_reasoning: false,
      supports_caching: true,
      supports_batch: true,
      max_tools_per_request: 128,
      max_images_per_request: 30,
    },
    endpoints: [
      {
        endpoint_id: 'openai-primary',
        base_url: 'https://api.openai.com/v1',
        region: 'us-east-1',
        max_concurrent_requests: 100,
        supports_streaming: true,
        credential_env_var: 'OPENAI_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 5000, tokens_per_minute: 800000, concurrent_requests: 100, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 1100, p95_latency_ms: 2800, reliability_score: 0.99 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal', 'confidential', 'restricted'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  // ─── GOOGLE ─────────────────────────────────────────────────────────────
  {
    model_id: 'google/gemini-2.0-flash@latest',
    provider: 'google',
    family: 'gemini',
    display_name: 'Gemini 2.0 Flash',
    tier: 'advanced',
    license: 'commercial_hosted',
    deployment_mode: 'hosted_api',
    context_window_tokens: 1000000,
    max_output_tokens: 8192,
    capabilities: [
      { capability_id: 'reason.fast', declared_quality_score: 0.90, preferred: false },
      { capability_id: 'vision.understand', declared_quality_score: 0.94, preferred: false },
      { capability_id: 'vision.chart', declared_quality_score: 0.95, preferred: true },
      { capability_id: 'audio.transcribe', declared_quality_score: 0.93, preferred: true },
    ],
    cost: { input_per_million_usd: 0.10, output_per_million_usd: 0.40 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: true,
      supports_vision: true,
      supports_audio: true,
      supports_json_mode: true,
      supports_structured_output: true,
      supports_streaming: true,
      supports_reasoning: false,
      supports_caching: true,
      supports_batch: false,
      max_tools_per_request: 64,
      max_images_per_request: 100,
    },
    endpoints: [
      {
        endpoint_id: 'google-primary',
        base_url: 'https://generativelanguage.googleapis.com/v1beta',
        region: 'us-east-1',
        max_concurrent_requests: 50,
        supports_streaming: true,
        credential_env_var: 'GOOGLE_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 1000, tokens_per_minute: 1000000, concurrent_requests: 50, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 600, p95_latency_ms: 1500, reliability_score: 0.98 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal', 'confidential'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },

  // ─── OPENROUTER (Fallback Router) ───────────────────────────────────────
  {
    model_id: 'openrouter/auto',
    provider: 'openrouter',
    family: 'openrouter',
    display_name: 'OpenRouter Universal Fallback',
    tier: 'standard',
    license: 'commercial_hosted',
    deployment_mode: 'hosted_api',
    context_window_tokens: 128000,
    max_output_tokens: 4096,
    capabilities: [
      { capability_id: 'reason.standard', declared_quality_score: 0.85, preferred: false },
      { capability_id: 'code.gen.short', declared_quality_score: 0.85, preferred: false },
    ],
    cost: { input_per_million_usd: 1.00, output_per_million_usd: 3.00 },
    features: {
      supports_tool_calling: true,
      supports_parallel_tools: false,
      supports_vision: true,
      supports_audio: false,
      supports_json_mode: true,
      supports_structured_output: false,
      supports_streaming: true,
      supports_reasoning: false,
      supports_caching: false,
      supports_batch: false,
      max_tools_per_request: 16,
      max_images_per_request: 5,
    },
    endpoints: [
      {
        endpoint_id: 'openrouter-primary',
        base_url: 'https://openrouter.ai/api/v1',
        region: 'us-east-1',
        max_concurrent_requests: 50,
        supports_streaming: true,
        credential_env_var: 'OPENROUTER_API_KEY',
        health: { state: 'healthy' },
      },
    ],
    rate_limits: { requests_per_minute: 500, tokens_per_minute: 200000, concurrent_requests: 50, daily_request_quota: 0, daily_token_quota: 0 },
    performance: { median_latency_ms: 1800, p95_latency_ms: 4500, reliability_score: 0.95 },
    eligibility: { allowed_tenants: [], blocked_tenants: [], allowed_regions: [], max_sensitivity: ['public', 'internal'], requires_baa: false, requires_dpa: false, data_residency_enforced: false, tier_restrictions: [] },
    registered_at_unix_ms: Date.now(),
  },
];

