import { z } from 'zod';
import { Sensitivity } from './enums';
import { Sha256HexSchema } from './shared';

export const CocoEventSchema = z.object({
  event_id: z.string(),
  event_type: z.string(),
  event_schema_version: z.number().int().positive().default(1),
  actor_kind: z.enum(['agent', 'user', 'system', 'external']),
  actor_id: z.string(),
  subject_kind: z.string(),
  subject_id: z.string().optional(),
  data: z.record(z.string(), z.unknown()).default({}),
  metadata: z.record(z.string(), z.unknown()).default({}),
  occurred_at_unix_ms: z.number().int().nonnegative(),
  sequence_number: z.number().int().nonnegative(),
  organization_id: z.string(),
  mission_id: z.string().optional(),
  run_id: z.string().optional(),
  task_id: z.string().optional(),
  correlation_id: z.string().optional(),
  causation_id: z.string().optional(),
  emitter_fabric: z.string(),
  emitter_component: z.string(),
  sensitivity: Sensitivity.default('internal'),
  payload_hash: Sha256HexSchema,
});
export type CocoEvent = z.infer<typeof CocoEventSchema>;

export const EVENT_TYPES = {
  MISSION_CREATED: 'mission.created',
  MISSION_UNDERSTANDING_STARTED: 'mission.understanding_started',
  MISSION_UNDERSTANDING_COMPLETED: 'mission.understanding_completed',
  MISSION_CHALLENGED: 'mission.challenged',
  MISSION_PLANNED: 'mission.planned',
  MISSION_ORGANIZED: 'mission.organized',
  MISSION_EXECUTING_STARTED: 'mission.executing_started',
  MISSION_VERIFIED: 'mission.verified',
  MISSION_REPAIRING_STARTED: 'mission.repairing_started',
  MISSION_REPAIR_COMPLETED: 'mission.repair_completed',
  MISSION_DELIVERING_STARTED: 'mission.delivering_started',
  MISSION_COMPLETED: 'mission.completed',
  MISSION_FAILED: 'mission.failed',
  MISSION_CANCELLED: 'mission.cancelled',
  MISSION_CHECKPOINT_CREATED: 'mission.checkpoint_created',
  MISSION_CHECKPOINT_RESTORED: 'mission.checkpoint_restored',
  MISSION_BUDGET_WARNING: 'mission.budget_warning',
  MISSION_BUDGET_EXCEEDED: 'mission.budget_exceeded',
  TASK_CREATED: 'task.created',
  TASK_STATUS_CHANGED: 'task.status_changed',
  TASK_ASSIGNED: 'task.assigned',
  TASK_STARTED: 'task.started',
  TASK_BLOCKED: 'task.blocked',
  TASK_COMPLETED: 'task.completed',
  TASK_FAILED: 'task.failed',
  TASK_DEPENDENCY_SATISFIED: 'task.dependency_satisfied',
  TASK_REPAIR_SCHEDULED: 'task.repair_scheduled',
  AGENT_SPAWN_REQUESTED: 'agent.spawn_requested',
  AGENT_SPAWNED: 'agent.spawned',
  AGENT_ASSIGNED: 'agent.assigned',
  AGENT_RUN_STARTED: 'agent.run_started',
  AGENT_MODEL_CALL_ISSUED: 'agent.model_call_issued',
  AGENT_TOOL_CALL_ISSUED: 'agent.tool_call_issued',
  AGENT_ASSUMPTION_RECORDED: 'agent.assumption_recorded',
  AGENT_FINDING_RECORDED: 'agent.finding_recorded',
  AGENT_RUN_COMPLETED: 'agent.run_completed',
  AGENT_RUN_FAILED: 'agent.run_failed',
  AGENT_RETIRED: 'agent.retired',
  AGENT_PAUSED: 'agent.paused',
  AGENT_RESUMED: 'agent.resumed',
  MODEL_ROUTE_REQUESTED: 'model.route_requested',
  MODEL_ROUTE_DECIDED: 'model.route_decided',
  MODEL_CALL_STARTED: 'model.call_started',
  MODEL_CALL_COMPLETED: 'model.call_completed',
  MODEL_CALL_FAILED: 'model.call_failed',
  MODEL_FALLBACK_TRIGGERED: 'model.fallback_triggered',
  MODEL_RATE_LIMITED: 'model.rate_limited',
  TOOL_INVOCATION_REQUESTED: 'tool.invocation_requested',
  TOOL_INVOCATION_APPROVED: 'tool.invocation_approved',
  TOOL_INVOCATION_DENIED: 'tool.invocation_denied',
  TOOL_SANDBOX_ALLOCATED: 'tool.sandbox_allocated',
  TOOL_EXECUTION_STARTED: 'tool.execution_started',
  TOOL_EXECUTION_COMPLETED: 'tool.execution_completed',
  TOOL_EXECUTION_FAILED: 'tool.execution_failed',
  TOOL_HUMAN_APPROVAL_REQUESTED: 'tool.human_approval_requested',
  TOOL_HUMAN_APPROVAL_GRANTED: 'tool.human_approval_granted',
  CONTEXT_PACKET_COMPILED: 'context.packet_compiled',
  MEMORY_WRITTEN: 'memory.written',
  MEMORY_SUPERSEDED: 'memory.superseded',
  MEMORY_CONTRADICTED: 'memory.contradicted',
  DECISION_RECORDED: 'decision.recorded',
  EVIDENCE_ADDED: 'evidence.added',
  VERIFICATION_STARTED: 'verification.started',
  VERIFICATION_LEVEL_PASSED: 'verification.level_passed',
  VERIFICATION_LEVEL_FAILED: 'verification.level_failed',
  VERIFICATION_ARTIFACT_ACCEPTED: 'verification.artifact_accepted',
  VERIFICATION_ARTIFACT_REJECTED: 'verification.artifact_rejected',
  CRITIC_REVIEW_STARTED: 'critic.review_started',
  CRITIC_REVIEW_COMPLETED: 'critic.review_completed',
  SECURITY_POLICY_VIOLATED: 'security.policy_violated',
  SECURITY_PERMISSION_DENIED: 'security.permission_denied',
  SECURITY_CAPABILITY_TOKEN_ISSUED: 'security.capability_token_issued',
  SECURITY_CAPABILITY_TOKEN_REVOKED: 'security.capability_token_revoked',
  SECURITY_HUMAN_APPROVAL_REQUIRED: 'security.human_approval_required',
  SECURITY_DESTRUCTIVE_ACTION_BLOCKED: 'security.destructive_action_blocked',
  SECURITY_RATE_LIMIT_EXCEEDED: 'security.rate_limit_exceeded',
  EVOLUTION_METRIC_RECORDED: 'evolution.metric_recorded',
  EVOLUTION_ROUTE_POLICY_UPDATED: 'evolution.route_policy_updated',
  EVOLUTION_AGENT_SCORE_UPDATED: 'evolution.agent_score_updated',
  EVOLUTION_MODEL_SCORE_UPDATED: 'evolution.model_score_updated',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];
