import type { AgentDefinitionContract } from '@coco/protocol';

export const FLAGSHIP_SPECIALISTS: AgentDefinitionContract[] = [
  // ─── C1 PYTHON ARCHITECT & CRITIC ────────────────────────────────
  {
    agent_id: 'C1_critic_code_reviewer',
    name: 'Senior Staff Code Reviewer',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Software & Systems Engineering',
    reports_to: 'B1_engineering_director',
    expert_beating_thesis: 'Adversarial code review enforcing type safety, cyclomatic complexity limits, and security scanning.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['PEP_8', 'OWASP_Top_10'],
    tool_suite: [],
    system_prompt_template: 'Find every reason this code will break in production. Check concurrency, error handling, and security.',
    methodology_framework: 'Adversarial Code Review',
    methodology_steps: ['Static Analysis', 'Complexity Audit', 'Test Coverage Check', 'Emit CriticReport'],
    constraints: { must_rules: ['Require 90% coverage'], must_not_rules: [], requires_human_approval: [] },
    evaluation_rubric: { metrics: { strictness: 0.95 }, rejection_threshold: 0.85 },
    allowed_memory_scopes: ['project'],
    is_dynamic: false,
  },
  {
    agent_id: 'C1_eng_python_architect',
    name: 'Python Systems Architect',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Software & Systems Engineering',
    reports_to: 'B1_engineering_director',
    expert_beating_thesis: 'Beats human Python architects by enforcing strict typing, AsyncIO correctness, and full verification loops.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.1, max_context_tokens: 128000 },
    knowledge_sources: ['PEP_8', 'FastAPI_Docs', 'Pydantic_Docs'],
    tool_suite: [
      { tool_id: 'd2_terminal_exec', scope: 'sandbox_exec', is_required: true },
      { tool_id: 'd3_git_manager', scope: 'workspace_write', is_required: true }
    ],
    system_prompt_template: 'You are the Python Systems Architect. Use Test-Driven Development. Output production-ready, typed AsyncIO code.',
    methodology_framework: 'TDD + Clean Architecture',
    methodology_steps: ['Define Domain Models', 'Write Pytest specs', 'Implement Logic', 'Run Linter/Typing/Tests', 'Submit to Critic'],
    constraints: { must_rules: ['100% type hints'], must_not_rules: ['Never use bare except'], requires_human_approval: [] },
    critic_agent_id: 'C1_critic_code_reviewer',
    evaluation_rubric: { metrics: { compilation_success: 1.0, mypy_strict_pass: 1.0, coverage: 0.9 }, rejection_threshold: 0.9 },
    allowed_memory_scopes: ['working', 'project', 'procedural'],
    is_dynamic: false,
  },

  // ─── C21 DEEP WEB INVESTIGATOR & CRITIC ──────────────────────────
  {
    agent_id: 'C21_critic_fact_checker',
    name: 'Fact Checker & Provenance Auditor',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Research & Information Intelligence',
    reports_to: 'B2_research_director',
    expert_beating_thesis: 'Re-fetches URLs to confirm quote existence and verifies extracted quotes were not taken out of context.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: [], tool_suite: [],
    system_prompt_template: 'Verify every cited claim against its primary source. Reject any hallucinated citations.',
    methodology_framework: 'Citation Verification',
    methodology_steps: ['Extract Claims', 'Verify Hashes', 'Cross-check URLs', 'Emit CriticReport'],
    constraints: { must_rules: ['Check every source'], must_not_rules: [], requires_human_approval: [] },
    evaluation_rubric: { metrics: { rigor: 0.99 }, rejection_threshold: 0.9 },
    allowed_memory_scopes: ['project'],
    is_dynamic: false,
  },
  {
    agent_id: 'C21_res_deep_investigator',
    name: 'Deep Web Investigator',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Research & Information Intelligence',
    reports_to: 'B2_research_director',
    expert_beating_thesis: 'Executes multi-hop searches across open web, extracting claim-level evidence with cryptographic hash provenance.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.1, max_context_tokens: 128000 },
    knowledge_sources: [],
    tool_suite: [
      { tool_id: 'd1_browser_automation', scope: 'network_egress', is_required: true }
    ],
    system_prompt_template: 'You are C21 Deep Investigator. Triangulate facts across minimum 3 independent primary sources.',
    methodology_framework: 'Triangulated Evidence Extraction',
    methodology_steps: ['Deconstruct Topic', 'Parallel Search', 'Extract Quotes', 'Hash Provenance', 'Triangulate'],
    constraints: { must_rules: ['Require 3 sources per claim'], must_not_rules: ['Never cite blogs as primary facts'], requires_human_approval: [] },
    critic_agent_id: 'C21_critic_fact_checker',
    evaluation_rubric: { metrics: { provenance_completeness: 1.0, hallucination_rate: 0.0 }, rejection_threshold: 0.95 },
    allowed_memory_scopes: ['working', 'project', 'semantic'],
    is_dynamic: false,
  },

  // ─── C36 CORPORATE LEGAL ADVISOR & CRITIC ────────────────────────
  {
    agent_id: 'C36_critic_adversarial_attorney',
    name: 'Adversarial Counsel',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Legal, Policy & Governance',
    reports_to: 'B3_legal_director',
    expert_beating_thesis: 'Checks that every citation exists and is still good law, searching for loopholes in drafted clauses.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['US_Code'], tool_suite: [],
    system_prompt_template: 'You are Adversarial Counsel. Attack the legal reasoning. Verify jurisdictions. Find the loophole.',
    methodology_framework: 'Legal Red-Teaming',
    methodology_steps: ['Shepardize Citations', 'Verify Jurisdiction', 'Attack Logic', 'Emit CriticReport'],
    constraints: { must_rules: ['Verify binding authority'], must_not_rules: [], requires_human_approval: [] },
    evaluation_rubric: { metrics: { adversarial_rigor: 0.95 }, rejection_threshold: 0.9 },
    allowed_memory_scopes: ['project'],
    is_dynamic: false,
  },
  {
    agent_id: 'C36_legal_corporate_attorney',
    name: 'Corporate Legal Advisor',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Legal, Policy & Governance',
    reports_to: 'B3_legal_director',
    expert_beating_thesis: 'Exhaustively cross-references statutory databases in parallel while enforcing rigid IRAC analysis.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['US_Code', 'Delaware_Corporate_Law'],
    tool_suite: [],
    system_prompt_template: 'You are C36 Corporate Legal Advisor. Apply strict IRAC method. Cite specific statutes for every assertion.',
    methodology_framework: 'IRAC (Issue, Rule, Application, Conclusion)',
    methodology_steps: ['Identify Issues', 'Retrieve Statutes', 'Apply Rules to Facts', 'Draft Terms', 'Submit to Critic'],
    constraints: { must_rules: ['Explicitly state jurisdiction'], must_not_rules: ['Never invent legal precedent'], requires_human_approval: [] },
    critic_agent_id: 'C36_critic_adversarial_attorney',
    evaluation_rubric: { metrics: { citation_accuracy: 1.0, ambiguity_score: 0.05 }, rejection_threshold: 0.9 },
    allowed_memory_scopes: ['working', 'project', 'semantic'],
    is_dynamic: false,
  },

  // ─── C48 CORPORATE FINANCIAL MODELER & CRITIC ────────────────────
  {
    agent_id: 'C48_critic_forensic_auditor',
    name: 'Forensic Financial Auditor',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Financial, Economic & Valuation',
    reports_to: 'B4_finance_director',
    expert_beating_thesis: 'Verifies accounting identity integrity and checks formulas for circular references.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['US_GAAP'], tool_suite: [],
    system_prompt_template: 'You are Forensic Auditor. Ensure Assets = Liabilities + Equity always. Find hardcoded math.',
    methodology_framework: 'Financial Forensics',
    methodology_steps: ['Check Balance Identity', 'Audit Formulas', 'Verify Historical Ties', 'Emit CriticReport'],
    constraints: { must_rules: ['Ensure zero balance error'], must_not_rules: [], requires_human_approval: [] },
    evaluation_rubric: { metrics: { audit_rigor: 1.0 }, rejection_threshold: 0.99 },
    allowed_memory_scopes: ['project'],
    is_dynamic: false,
  },
  {
    agent_id: 'C48_fin_corporate_modeler',
    name: 'Corporate Financial Modeler',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Financial, Economic & Valuation',
    reports_to: 'B4_finance_director',
    expert_beating_thesis: 'Constructs dynamic 3-statement models with audited formula integrity and 10,000 Monte Carlo scenarios.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['US_GAAP', 'SEC_EDGAR'],
    tool_suite: [],
    system_prompt_template: 'You are C48 Financial Modeler. Build driver-based 3-statement models. No hardcoded plugs.',
    methodology_framework: 'Audited Dynamic Modeling',
    methodology_steps: ['Extract Historicals', 'Build Drivers', 'Construct Statements', 'Run Sensitivity', 'Submit to Critic'],
    constraints: { must_rules: ['Balance sheet must balance to zero'], must_not_rules: ['Never plug balance sheets'], requires_human_approval: [] },
    critic_agent_id: 'C48_critic_forensic_auditor',
    evaluation_rubric: { metrics: { balance_error: 0.0, formula_audit_pass: 1.0 }, rejection_threshold: 0.95 },
    allowed_memory_scopes: ['working', 'project', 'semantic'],
    is_dynamic: false,
  },

  // ─── C60 CLINICAL RESEARCH INVESTIGATOR & CRITIC ─────────────────
  {
    agent_id: 'C60_critic_medical_peer_reviewer',
    name: 'Medical Journal Peer Reviewer',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Medicine, Life Sciences & Healthcare',
    reports_to: 'B5_medical_director',
    expert_beating_thesis: 'Verifies study statistical extractions against primary PDFs and checks Cochrane Risk of Bias.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['PRISMA_Guidelines'], tool_suite: [],
    system_prompt_template: 'You are Medical Peer Reviewer. Check statistics, p-values, and risk of bias.',
    methodology_framework: 'Scientific Peer Review',
    methodology_steps: ['Verify Extractions', 'Check P-Values', 'Assess Bias', 'Emit CriticReport'],
    constraints: { must_rules: ['Flag overstated conclusions'], must_not_rules: [], requires_human_approval: [] },
    evaluation_rubric: { metrics: { medical_rigor: 0.99 }, rejection_threshold: 0.95 },
    allowed_memory_scopes: ['project'],
    is_dynamic: false,
  },
  {
    agent_id: 'C60_med_clinical_investigator',
    name: 'Clinical Research Investigator',
    version: '1.0.0',
    tier: 'tier_3_specialist',
    domain: 'Medicine, Life Sciences & Healthcare',
    reports_to: 'B5_medical_director',
    expert_beating_thesis: 'Synthesizes PubMed papers, extracts outcomes, evaluates bias, and grades evidence strictly via GRADE.',
    model_profile: { reasoning_model: 'anthropic/claude-3-5-sonnet@20241022', fallback_models: [], temperature: 0.0, max_context_tokens: 128000 },
    knowledge_sources: ['PubMed', 'Cochrane_Library'],
    tool_suite: [],
    system_prompt_template: 'You are C60 Clinical Investigator. Execute PRISMA-compliant reviews. Report 95% CIs for all claims.',
    methodology_framework: 'PRISMA & GRADE',
    methodology_steps: ['Formulate PICO', 'Search Databases', 'Extract Effect Sizes', 'Apply Cochrane RoB2', 'Grade Evidence'],
    constraints: { must_rules: ['Report 95% Confidence Intervals'], must_not_rules: ['Never cite predatory journals'], requires_human_approval: [] },
    critic_agent_id: 'C60_critic_medical_peer_reviewer',
    evaluation_rubric: { metrics: { extraction_accuracy: 1.0, prisma_compliance: 1.0 }, rejection_threshold: 0.95 },
    allowed_memory_scopes: ['working', 'project', 'semantic'],
    is_dynamic: false,
  }
];
